paths:
  "/error":
    get:
      description: Retrieve error documentation
      responses:
        200:
          description: Success
        404:
          description: Not found
        500:
          description: Internal server error